# Generated by Django 4.2.4 on 2023-10-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitName', models.CharField(max_length=100)),
                ('unitCode', models.CharField(default='#001P', max_length=50)),
                ('supplierName', models.CharField(default='S.A', max_length=50)),
                ('unitAmount', models.CharField(max_length=6)),
                ('totalAmountCLP', models.CharField(max_length=15)),
                ('shippingCLP', models.CharField(max_length=15)),
                ('customCLP', models.CharField(max_length=15)),
                ('ivaCLP', models.CharField(max_length=15)),
                ('totalTaxesCLP', models.CharField(max_length=15)),
                ('totalPurchaseCLP', models.CharField(max_length=15)),
                ('totalPurchaseUSD', models.CharField(max_length=15)),
            ],
        ),
    ]
